/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import com.formdev.flatlaf.FlatIntelliJLaf;
import entidades.*;
import estructuras.*;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author OMEN
 */
public class FrmRegistroCliente extends javax.swing.JFrame {
    
    Cliente c = new Cliente();
    ListaCircular ListDescuentos = new ListaCircular();
    /**
     * Creates new form FrmRegistroCliente
     */
    public FrmRegistroCliente() {
        initComponents();
        setSize(444, 420);
        ListDescuentos.insertarFinal(10);
        ListDescuentos.insertarFinal(20);
        ListDescuentos.insertarFinal(30);
        ListDescuentos.insertarFinal(40);
        ListDescuentos.insertarFinal(50);
        ListDescuentos.insertarFinal(60);
        ListDescuentos.insertarFinal(70);
        ListDescuentos.insertarFinal(80);
        ListDescuentos.insertarFinal(90);
    }

    public ListaCircular getListDescuentos() {
        return ListDescuentos;
    }

    public void setListDescuentos(ListaCircular ListDescuentos) {
        this.ListDescuentos = ListDescuentos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttnGrupo1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrbEsporadico = new javax.swing.JRadioButton();
        jrbtHabitual = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnDescuento = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        txtNombre = new componentes.TextField();
        txtApellido = new componentes.TextField();
        txtDni = new componentes.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttnGrupo1.add(jrbEsporadico);
        jrbEsporadico.setText("Cliente Esporadico");
        jrbEsporadico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEsporadicoActionPerformed(evt);
            }
        });
        jPanel1.add(jrbEsporadico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 147, -1));

        bttnGrupo1.add(jrbtHabitual);
        jrbtHabitual.setText("Cliente Habitual");
        jrbtHabitual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtHabitualActionPerformed(evt);
            }
        });
        jPanel1.add(jrbtHabitual, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 132, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 50, 210, -1));

        btnGuardar.setBackground(new java.awt.Color(40, 75, 99));
        btnGuardar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 132, 37));

        btnDescuento.setBackground(new java.awt.Color(40, 75, 99));
        btnDescuento.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnDescuento.setForeground(new java.awt.Color(255, 255, 255));
        btnDescuento.setText("Sorteo descuento");
        btnDescuento.setEnabled(false);
        btnDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescuentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 147, 37));

        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAtras.setText("←");
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        txtNombre.setLabelText("Nombre");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 200, -1));

        txtApellido.setLabelText("Apellidos");
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 200, -1));

        txtDni.setLabelText("Dni");
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    public Cliente getC() {
        return c;
    }

    public void setC(Cliente c) {
        this.c = c;
    }

    
    
    private void btnDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentoActionPerformed
        this.setVisible(false);
        FrmDescuentos z = new FrmDescuentos();
        z.setFrm(this);
        z.setVisible(true);
    }//GEN-LAST:event_btnDescuentoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre,apellido,dni;
        if(!txtNombre.getText().trim().equals("")){
            nombre = txtNombre.getText();
            if(!txtApellido.getText().trim().equals("")){
                apellido = txtApellido.getText();
                if (txtDni.getText().length()==8){
                    dni = txtDni.getText();
                    if (jrbEsporadico.isSelected()){
                        c.setApellido(apellido);
                        c.setNombre(nombre);
                        c.setDni(dni);
                        //c = new Cliente(nombre, apellido, dni);
                        c.setEsHabitual(false);
                        c.setDescuento(0.0);
                        JOptionPane.showMessageDialog(this, "Datos del cliente: \n- Nombre: "+c.getNombre()+"\n- Apellido: "+c.getApellido()+"\n- Tipo de cliente: Esporadico\n- Descuento: "+c.getDescuento(), "Cliente registrado con Exito", 1);
                        Clientes.insertar(c);
                        limpiarCajas();
                        dispose();
                        
                    }else{
                        if (jrbtHabitual.isSelected()){
                            //c = new Cliente(nombre, apellido, dni);
                            c.setApellido(apellido);
                            c.setNombre(nombre);
                            c.setDni(dni);
                            c.setEsHabitual(true); 
                            JOptionPane.showMessageDialog(this, "Datos del cliente: \n- Nombre: "+c.getNombre()+"\n- Apellido: "+c.getApellido()+"\n- Tipo de cliente: Habitual\n- Descuento: "+c.getDescuento(), "Cliente registrado con Exito", 1);
                            Clientes.insertar(c);
                            limpiarCajas();
                            dispose();
                            
                        }else{
                            JOptionPane.showMessageDialog(this, "Seleccione que tipo de cliente es por favor", "Error", 0);
                        }
                    }

                }else{
                    JOptionPane.showMessageDialog(this, "Ingrese un numero con 8 digitos por favor", "Error", 0);
                    txtDni.setText(null);
                    txtDni.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(this, "Ingrese un apellido por favor", "Error", 0);
                txtApellido.requestFocus();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese un nombre por favor", "Error", 0);
            txtNombre.requestFocus();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jrbtHabitualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtHabitualActionPerformed
        if(jrbtHabitual.isSelected() && !txtNombre.getText().trim().equals("") && !txtApellido.getText().trim().equals("") && txtDni.getText().length()==8)
            btnDescuento.setEnabled(true);
        
    }//GEN-LAST:event_jrbtHabitualActionPerformed

    private void jrbEsporadicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEsporadicoActionPerformed
        if (jrbEsporadico.isSelected()) 
            btnDescuento.setEnabled(false);
    }//GEN-LAST:event_jrbEsporadicoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        jPanel1.requestFocus();
    }//GEN-LAST:event_jPanel1MouseClicked
    
    public void limpiarCajas(){
        txtApellido.setText(null);
        txtDni.setText(null);
        txtNombre.setText(null);
        bttnGrupo1.clearSelection();
        txtNombre.requestFocus();
        btnDescuento.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           FlatIntelliJLaf.registerCustomDefaultsSource("style");  
           FlatIntelliJLaf.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnDescuento;
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup bttnGrupo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbEsporadico;
    private javax.swing.JRadioButton jrbtHabitual;
    private componentes.TextField txtApellido;
    private componentes.TextField txtDni;
    private componentes.TextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
