/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.*;
import com.formdev.flatlaf.intellijthemes.*;
import frames.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.UIManager;

/**
 *
 * @author DEYSI
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        jPanel1.requestFocus();
        btnOp1.putClientProperty("JButton.buttonType", "roundRect");
        btnOp2.putClientProperty("JButton.buttonType", "roundRect");
        btnOp3.putClientProperty("JButton.buttonType", "roundRect");
        btnOp4.putClientProperty("JButton.buttonType", "roundRect");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        btnOp1 = new javax.swing.JButton();
        btnOp2 = new javax.swing.JButton();
        btnOp3 = new javax.swing.JButton();
        btnOp4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOp1.setBackground(new java.awt.Color(0, 102, 102));
        btnOp1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        btnOp1.setForeground(new java.awt.Color(255, 255, 255));
        btnOp1.setText("Reservas");
        btnOp1.setBorderPainted(false);
        btnOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 660, 180, 50));

        btnOp2.setBackground(new java.awt.Color(0, 102, 102));
        btnOp2.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        btnOp2.setForeground(new java.awt.Color(255, 255, 255));
        btnOp2.setText("Nuevo Cliente");
        btnOp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 180, 50));

        btnOp3.setBackground(new java.awt.Color(0, 102, 102));
        btnOp3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        btnOp3.setForeground(new java.awt.Color(255, 255, 255));
        btnOp3.setText("Reservar");
        btnOp3.setBorderPainted(false);
        btnOp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 660, 180, 50));

        btnOp4.setBackground(new java.awt.Color(0, 102, 102));
        btnOp4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        btnOp4.setForeground(new java.awt.Color(255, 255, 255));
        btnOp4.setText("Clientes");
        btnOp4.setBorderPainted(false);
        btnOp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOp4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 660, 180, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 900, 110));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Georgia", 3, 58)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("  HOTEL POLLITO CARIÑOSO  ");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 960, 90));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hotel.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 670));

        jPanel10.setBackground(new java.awt.Color(217, 217, 217));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 20));

        jPanel11.setBackground(new java.awt.Color(217, 217, 217));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1030, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 640, 1, -1));

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon.png"))); // NOI18N
        jMenu2.setText("Registro");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clicli.png"))); // NOI18N
        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reser.png"))); // NOI18N
        jMenuItem2.setText("Reserva");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lista.png"))); // NOI18N
        jMenu3.setText("Listas");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clicli.png"))); // NOI18N
        jMenuItem3.setText("Clientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reser.png"))); // NOI18N
        jMenuItem4.setText("Reservas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp1ActionPerformed
        MostrarReservas f = new MostrarReservas();
        f.setVisible(true);
        this.setVisible(false);
        f.addWindowListener(new WindowAdapter() {
            @Override
                            public void windowClosed(WindowEvent e) {
                                Menu.this.setVisible(true);
                                jPanel1.requestFocus();
                            }
        });
    }//GEN-LAST:event_btnOp1ActionPerformed

    private void btnOp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp2ActionPerformed
        FrmRegistroCliente f = new FrmRegistroCliente();
        f.setVisible(true);
        this.setVisible(false);
        f.addWindowListener(new WindowAdapter() {
            @Override
                            public void windowClosed(WindowEvent e) {
                                Menu.this.setVisible(true);
                                jPanel1.requestFocus();
                            }
        });
    }//GEN-LAST:event_btnOp2ActionPerformed

    private void btnOp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp3ActionPerformed
        FrmReservarHabitacion f = new FrmReservarHabitacion();
        f.setVisible(true);
        this.setVisible(false);
        f.addWindowListener(new WindowAdapter() {
            @Override
                            public void windowClosed(WindowEvent e) {
                                Menu.this.setVisible(true);
                                jPanel1.requestFocus();
                            }
        });
    }//GEN-LAST:event_btnOp3ActionPerformed

    private void btnOp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOp4ActionPerformed
        ListadoClientes f = new ListadoClientes();
        f.setVisible(true);
        this.setVisible(false);
        f.addWindowListener(new WindowAdapter() {
            @Override
                            public void windowClosed(WindowEvent e) {
                                Menu.this.setVisible(true);
                                jPanel1.requestFocus();
                            }
        });
    }//GEN-LAST:event_btnOp4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmRegistroCliente f = new FrmRegistroCliente();
        f.setVisible(true);
        this.setVisible(false);
        f.addWindowListener(new WindowAdapter() {
            @Override
                            public void windowClosed(WindowEvent e) {
                                Menu.this.setVisible(true);
                                jPanel1.requestFocus();
                            }
        });
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmReservarHabitacion f = new FrmReservarHabitacion();
        f.setVisible(true);
        this.setVisible(false);
        f.addWindowListener(new WindowAdapter() {
            @Override
                            public void windowClosed(WindowEvent e) {
                                Menu.this.setVisible(true);
                                jPanel1.requestFocus();
                            }
        });
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ListadoClientes f = new ListadoClientes();
        f.setVisible(true);
        this.setVisible(false);
        f.addWindowListener(new WindowAdapter() {
            @Override
                            public void windowClosed(WindowEvent e) {
                                Menu.this.setVisible(true);
                                jPanel1.requestFocus();
                            }
        });
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        MostrarReservas f = new MostrarReservas();
        f.setVisible(true);
        this.setVisible(false);
        f.addWindowListener(new WindowAdapter() {
            @Override
                            public void windowClosed(WindowEvent e) {
                                Menu.this.setVisible(true);
                                jPanel1.requestFocus();
                            }
        });
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
           FlatIntelliJLaf.registerCustomDefaultsSource("style");  
           FlatIntelliJLaf.setup();
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOp1;
    private javax.swing.JButton btnOp2;
    private javax.swing.JButton btnOp3;
    private javax.swing.JButton btnOp4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
